### ISSUE TITLE
Send π to this address!GDF3BWWZVZZPZ6MNAHQIFH2T5FJQ4CCE3FLASPGNGW325NWR6D4HPPMX

### ISSUE THREAD

**Issue by 1234567891011111112227** [1234567891011111112227/pi-explorer#15]
GDF3BWWZVZZPZ6MNAHQIFH2T5FJQ4CCE3FLASPGNGW325NWR6D4HPPMX![IMG_20231201_001900.jpg](https://github.com/1234567891011111112227/pi-explorer/assets/123794341/6fda2801-4e53-402d-8c0c-358b898294d4)

![IMG_20231201_001826.jpg](https://github.com/1234567891011111112227/pi-explorer/assets/123794341/ce3f4d8e-db6d-4e0d-ad24-4e8475a4bb39)

**Comment by evandrofgarcia** [comment]
Wonderful
